name: fail-test

on:
  push:
    branches:
      - main

jobs:
  test-failure:
    runs-on: ubuntu-latest
    steps:
      - name: This will fail on purpose
        run: |
          echo "About to fail 😈"
          exit 1
